name: pgai
services:
  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/home/postgres/pgdata/data
    networks:
      - ollama-network
  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/pgaidatabase
      OLLAMA_HOST: http://ollama-embedder:11436
    command: [ "--poll-interval", "5s" ]
    depends_on:
      - db
      - ollama-embedder
    networks:
      - ollama-network
  ollama-chat:
    image: ollama/ollama
    ports:
      - "11434:11434"
    container_name: ollama-chat
    volumes:
      - ollama-chat:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    networks:
      - ollama-network
    entrypoint: ["/bin/sh", "/ollama-entrypoint.sh"]
    # Make the entrypoint script executable
    user: root
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu      
  ollama-embedder:
    image: ollama/ollama
    ports:
      - "11436:11434"
    container_name: ollama-embedder
    volumes:
      - ollama-embedder:/root/.ollama
    networks:
      - ollama-network
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
  llama3-vision:
    image: ollama/ollama
    ports:
      - "11435:11434"
    container_name: llama3-vision
    networks:
      - ollama-network
    volumes:
      - llama3-vision-data:/root/.ollama
    command: ["ollama", "run", "llama3.2-vision"]
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    volumes:
      - ollama-chat:/root/.ollama
      - open-webui:/app/backend/data
    depends_on:
      - ollama-chat
    ports:
      - 3000:8080
    environment:
      - OLLAMA_API_BASE_URL=http://ollama-chat:11434
      - OLLAMA_BASE_URL=http://ollama-chat:11434
      - OLLAMA_API_KEY=
      - WEBUI_SECRET_KEY=
      - WEBUI_AUTH=false
      - WEBUI_ALLOW_REGISTRATION=true
      - WEBUI_ALLOW_REGISTRATION_DOMAINS=
      - WEBUI_DEFAULT_MODELS=llama3
    networks:
      - ollama-network
    restart: always
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
volumes:
  data:
  llama3-vision-data:
  open-webui:
  ollama-embedder:
  ollama-chat:

networks:
  ollama-network:
    driver: bridge