spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pgaidatabase?stringtype=unspecified
    username: postgres
   # password: my_pwd
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      isolation-level: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgresql
      continue-on-error: true
      schema-locations: 
        - classpath:schema-postgresql.sql
        - classpath:schema-documents.sql
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: READ_COMMITTED
      table-prefix: BATCH_
    job:
      enabled: false
    chunk-size: 10

logging:
  level:
    root: INFO
    com.johoco.springbatchpgaiapp: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

document:
  input:
    directory: C:/workspace/rag/langchain/poc/documents
    polling-interval: 5000
  output:
    directory: C:/workspace/rag/langchain/poc/documents/processed
    failed-directory: C:/workspace/rag/langchain/poc/documents/failed
