spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pgaidatabase?stringtype=unspecified
    username: postgres
    password: my_pwd
    driver-class-name: org.postgresql.Driver
    hikari:
      isolation-level: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgresql
      continue-on-error: true
      schema-locations: classpath:schema-postgresql.sql
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: READ_COMMITTED
      table-prefix: BATCH_
    job:
      enabled: false
    chunk-size: 10

logging:
  level:
    com.johoco.springbatchpgaiapp: DEBUG
    org.springframework.batch: INFO

document:
  input:
    directory: C:/workspace/rag/langchain/poc/documents
    polling-interval: 5000
